### PR TITLE
[GITHUB-1] Adds Supervisor install and config

### PR DESCRIPTION
**Pull request by lobsterdore**

### CODE REVIEW

**Review by rsgoodall — APPROVED** [review]
Looks fine.

**Comment by racer1680** [comment]
How is sansible_supervisor_conf_dir: better than sansible_supervisor: conf_dir: ?

**Comment by lobsterdore** [comment]
@racer1680 It doesn't require hash_behaviour: merge.

**Comment by sreddel** [comment]
simple, yet effective :+1:

**Pull request merged**
